name: Terraform Plan

on:
  push:
    branches:
      - master

env:
  TF_CLOUD_ORGANIZATION: "Martin_Org"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-demo"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/terraform-demo'
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
